version: '3.9'

services:
  knowledge-graph-db:
    container_name: knowledge-graph-db
    build:
      context: .
      dockerfile: Dockerfile.graphdb
      args:
        version: 10.2.2
    restart: unless-stopped
    environment:
      GDB_JAVA_OPTS: >-
        -Xmx2g -Xms2g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
    ports:
      - "7200:7200"
      - "7300:7300"
    volumes:
      - ./graphdb-data:/opt/graphdb/home
  knowledge-repository-app:
    container_name: knowledge-repository-app
    build:
      context: .
      dockerfile: Dockerfile.knowledge_repository
    ports:
      - "3001:3001"
    depends_on:
      - knowledge-graph-db