nl-feature-extraction.url=http://gessi-chatbots.essi.upc.edu:5000/extract-features
nl-sentiment-analysis-extraction.url=http://gessi-chatbots.essi.upc.edu:5000/review-extraction
inductive-knowledge-service.url=http://localhost:5001
registry.url=***************
db.url=http://gessi-chatbots.essi.upc.edu:7200/repositories/app-data-repo


#logging.file.path=******************************************************